### ISSUE TITLE
Photo for location

### ISSUE THREAD

**Issue by JonGaydos** [sysadminsmedia/homebox#216] opened 2024-09-11 13:42 UTC
### What is the problem you are trying to solve with this feature?

Enhancement, no problems

### What is the solution you are proposing?

I'd love to be able to upload a photo to the location of items, not just the items themselves.

On the homepage where all the locations are listed at the bottom, a small photo of whatever you want to visually identify the area in addition to the name. Also, on the location page itself, the top header (near the edit and delete button) is a larger photo of the area. 

### What alternatives have you considered?

No alternative, just a neat feature to have to enhance the program. 

### Contributions

- [X] I have searched through existing issues and feature requests to see if my idea has already been proposed.
- [ ] If this feature is accepted, I would be willing to help implement and maintain this feature.
- [X] If this feature is accepted, I'm willing to sponsor the development of this feature.

**Comment by katosdev** [comment] 2024-09-13 19:12
Seems like a no-brainer to me, tagging!

**Comment by katosdev** [comment] 2024-09-24 18:54
Duplicate of #52 - Closing.

**Comment by katosdev** [comment] 2024-09-24 18:54
Duplicate of #52 - Closing.

**Closed by katosdev** 2024-09-24 18:54 UTC
Labels: ⬆️ enhancement, 👷‍♂️ help wanted
