### ISSUE TITLE
Home page quick statistics labels not visible with homebox theme

### ISSUE THREAD

**Issue by davecburke** [sysadminsmedia/homebox#47] opened 2024-06-23 01:57 UTC
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### Homebox Version

v0.11.0

### What is the issue you are experiencing?

The Quick Statistics labels are not visible when using the Homebox theme. They are there but too dark to read

### How can the maintainer reproduce the issue?

Set the theme to Homebox and got to the home page
![image](https://github.com/sysadminsmedia/homebox/assets/148930542/2eb975ed-ae92-4adb-aef5-c103e2c6642c)

### Deployment

Docker (Linux)

**Comment by tankerkiller125** [comment] 2024-06-23 02:30
Duplicate of #34 

Will be fixed when next release (most likely a patch release) is published.

**Closed by tankerkiller125** 2024-06-23 02:30 UTC
Labels: bug
