### ISSUE TITLE
Recurring maintenance feature request.

### ISSUE THREAD

**Issue by imoldovavan** [sysadminsmedia/homebox#368] opened 2024-12-06 16:11 UTC
### What is the problem you are trying to solve with this feature?

Add the ability to add recurring maintenance tasks by allowing the user to select the recurring time interval: days, weeks, months, years. For example for a water heater, purge the pressure valve every year, or grease the blower motor on your furnace every 2 years. 

### What is the solution you are proposing?

When the user completes a recurring maintenance task, a new task is automatically created with a scheduled date that is automatically calculated from the completed date plus the recurring time interval.

### What alternatives have you considered?

At the moment the only way to do this is duplicate a task and do the math on the scheduled date.

### Contributions

- [x] I have searched through existing issues and feature requests to see if my idea has already been proposed.
- [ ] If this feature is accepted, I would be willing to help implement and maintain this feature.
- [ ] If this feature is accepted, I'm willing to sponsor the development of this feature.

**Comment by 101br03k** [comment] 2024-12-06 19:56
looks like a duplicate of https://github.com/sysadminsmedia/homebox/issues/172

**Closed** 2024-12-06 23:50 UTC
Labels: ⬆️ enhancement
