### ISSUE TITLE
Add New Zealand Dollar

### ISSUE THREAD

**Issue by nickrout** [sysadminsmedia/homebox#79] opened 2024-06-29 23:00 UTC
### What is the problem you are trying to solve with this feature?

NZD or NZ$ not available

### What is the solution you are proposing?

Add the New Zealand dollar

### What alternatives have you considered?

Looked at original hay-kot code

### Additional context

Nil

### Contributions

- [X] I have searched through existing issues and feature requests to see if my idea has already been proposed.
- [X] If this feature is accepted, I would be willing to help implement and maintain this feature.
- [X] If this feature is accepted, I'm willing to sponsor the development of this feature.

**Comment by nickrout** [comment] 2024-06-29 23:14
It seemed to have been added here https://github.com/hay-kot/homebox/pull/360/files but deleted here https://github.com/hay-kot/homebox/pull/685/files#diff-20fbe4c39b37c37c9ff0247f1fe81f8653dea361a79a0dc6fc609d7f39383f6dL59

**Comment by grbray** [comment] 2024-06-30 05:26
This is already part of #1 and should be closed.

**Comment by tankerkiller125** [comment] 2024-06-30 14:00
Going to remove this as a duplicate of #1

**Closed by tankerkiller125** 2024-06-30 14:00 UTC

**Comment by katosdev** [comment] 2024-06-30 14:53
FYI @nickrout - Aiming to fix in https://github.com/sysadminsmedia/homebox/pull/81

**Comment by nickrout** [comment] 2024-07-02 10:00
Thank you
